### ISSUE TITLE
Django plans cause error in sqlite3 backend

### ISSUE THREAD

**Issue by onlydarkknight** [django-getpaid/django-plans#167]
i have a web app hosted on pythonanywhere.com and i have installed django plans in a virtualenv. my python version is 3.8 and django is 3.2.12. My app and plan section works fine, but recently my app encouter some nasty errors in django and plans as bellow:
`
Internal Server Error: /
Traceback (most recent call last):
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/plans/views.py", line 120, in get_context_data
    context['plan_table'] = self.get_plan_table(self.object_list)
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/plans/views.py", line 74, in get_plan_table
    for plan in plan_list:
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/models/query.py", line 1263, in _fetch_all
    self._prefetch_related_objects()
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/models/query.py", line 782, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/models/query.py", line 1651, in prefetch_related_objects
    obj_list, additional_lookups = prefetch_one_level(obj_list, prefetcher, lookup, level)
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/models/query.py", line 1764, in prefetch_one_level
    prefetcher.get_prefetch_queryset(instances, lookup.get_current_queryset(level)))
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 635, in get_prefetch_queryset
    for rel_obj in queryset:
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/models/query.py", line 74, in __iter__
    for row in compiler.results_iter(results):
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1095, in apply_converters
    value = converter(value, expression, connection)
  File "/home/SocialAI/.virtualenvs/expertenv/lib/python3.8/site-packages/django/db/backends/sqlite3/operations.py", line 286, in converter
    return create_decimal(value).quantize(quantize_value, context=expression.output_field.context)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
 `
I post this error in pythonanywhere forum also,but so far no solution found for this issue.

**Comment by onlydarkknight** [comment]
No help!? no any idea or suggestions?!

**Comment by onlydarkknight** [comment]
Finally i found the solution and it was presaved records in database! So by deleting related records in datbase problem solved.
Just enabling "*DEBUG=True*" in app setting was required to control which data and value passed to functions
