### ISSUE TITLE
[bug] Error when migrate

### ISSUE THREAD

**Issue by paulocoutinhox** [django-getpaid/django-plans#192]
Hi,

When i execute migrate, i get errors:

```
Running migrations:
  Applying plans.0001_initial... OK
  Applying plans.0002_auto_20180901_1744... OK
  Applying plans.0003_make_plans_unique... OK
  Applying plans.0004_create_user_plans...Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/homebrew/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 354, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such column: plans_plan.updated_at
```

Can you help me?

Thanks.

**Comment by fatimaMarzouq** [comment]
Hello, i'm facing the same issue. did you manage to solve it?
@paulocoutinhox

**Comment by twkrol** [comment]
Same here, any resolution?

**Comment by twkrol** [comment]
My soluton: I've decided to fork the repo then commented out operations in the migration 0004 which causes problem. You can take a look at it:
https://github.com/twkrol/django-plans/blob/master/plans/migrations/0004_create_user_plans.py

**Comment by PetrDlouhy** [comment]
You could probably just skip that one migration by usage of  "--fake" option.
I am not sure about what is the right solution to fix that migration now, but I might look into it over time. But PRs are always wellcome.
